### ISSUE TITLE
Не работают интервальные часы.

### ISSUE THREAD

**Issue by UltraChannel000** [TheFUlDeep/gmod_addons#407]
Здравствуйте! У меня проблема, не работают интервальные часы на станциях(не реагируют на отправление составов). Как исправить данную проблему?

**Comment by TheFUlDeep** [comment]
В этом репозитории на интервальные часы может повлиять только вот этот файл [тык](https://github.com/TheFUlDeep/gmod_addons/blob/master/metrostroi_scripts/lua/thefuldeep_autorun/metrostroi_custom_time/custom_time.lua)
Но в нем, вроде, нет ошибок

**Comment by UltraChannel000** [comment]
Перезаписал этот самый файл, позже отпишусь.
